### ISSUE TITLE
End Remastered crash

### ISSUE THREAD

**Issue by MisakiCopperrose** [Fuzss/easymagic#1]
Hi all, there seems to be a weird bug when using this mod with TerraForged and End Remastered: [https://www.curseforge.com/minecraft/mc-mods/endremastered](url).

The game crashes when trying to load in the end castle containing a enchanting table. 
After removing Easy Magic there doesn't seem to be a problem anymore.

I'll add the crashlogs down below.
[crash-2021-03-17_15.04.29-client.txt](https://github.com/Fuzss/easymagic/files/6159222/crash-2021-03-17_15.04.29-client.txt)

**Comment by Fuzss** [comment]
Will be fixed in v1.0.2!

**Comment by MisakiCopperrose** [comment]
Perfect! :)

**Comment by Fuzss** [comment]
New version released on Curse.
