### ISSUE TITLE
[Issue] Render table contents

### ISSUE THREAD

**Issue by faelBrunnoS** [Fuzss/easymagic#12]
> To put the new inventory capability to good use, enchanting tables will Render Their Contents in the world. There are three different rendering modes to choose from.

This function described in Curse Forge has the following problem:

![image](https://user-images.githubusercontent.com/83606488/157556863-b2c0c8e4-4837-4709-af45-c5e7a8ac5d77.png)
Even being far away, the items don't go inside the book and are rendered anyway.
I don't know if this is from the Mod, but I don't think so, right?
In your other mod [Enchanting Infuser [Forge]](https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge) works normally, the item placed in the table slot goes back inside the book when you distance yourself.

I'm using this version [EasyMagic-v3.3.0-1.18.2-Forge.jar](https://www.curseforge.com/minecraft/mc-mods/easy-magic/files/3671353)
Minecraft 1.18.2
Forge 40.0.12

**Comment by Fuzss** [comment]
Thanks for the report, this is intentional. 

The Enchanting Infuser animation simply is a different one. I might add it to Easy Magic in a future update though.
