### ISSUE TITLE
You can re-roll an empty table

### ISSUE THREAD

**Issue by SodiumShine** [Fuzss/easymagic#13]
Very minor bug but when there's nothing to enchant in the slot, you can still re-roll repeatedly, wasting lapis and xp when re-roll cost is enabled.
EasyMagic-v3.3.0-1.18.2-Forge.jar
Forge - 40.1.60

**Comment by Fuzss** [comment]
Fixed in v4.0.0.

**Comment by SodiumShine** [comment]
Will this be available for 1.18.2 or are you only supporting versions going forward?

**Comment by Fuzss** [comment]
I don’t want to take the time to backport this, it’s not a serious issue.
