### ISSUE TITLE
[Crash]: Error Code 1 MC Launcher shows.

### ISSUE THREAD

**Issue by Ahley411** [Fuzss/easymagic#15]
### Mod Loader

Forge

### Minecraft Version

1.19.1

### Mod Version

v4.1.0-1.19.1

### Notes

Used with and without mods loaded. Error Code one. 

I had this crashing behavior with another one of your mods not being compatible with Optifine a few days ago, but this is loaded alone, so idk what could be the issue. Thanks for any help
![crash](https://user-images.githubusercontent.com/72476191/181997024-0ab7a586-50af-421f-8ec7-4d1172915e95.jpg)
.

### Crash Report 

https://gist.github.com/Ahley411/253aa766cef476e4b1653aa804416a1d

### latest.log

https://gist.github.com/Ahley411/58e311a7ef3d88ed784acfde2b217641

**Comment by Fuzss** [comment]
Crash report and log are unrelated. The crash is caused by ironfurnaces, the mod version you are using is not compatible with Forge 41.0.94+
For my mods you seem to have outdated versions, I just pushed a bunch of updates for 1.19.1, please use the latest versions and try again. Also make sure you‘ve installed Puzzles lib.

**Comment by Ahley411** [comment]
> 

After looking over, I realized I have sent the wrong crash report.
[latest.log](https://github.com/Fuzss/easymagic/files/9227792/latest.log)
After loading through the game with only PuzzlesLib and EasyMagic, I produced the log up above, for I cannot show a crash report. Apologies.

**Comment by Fuzss** [comment]
You have an outdated version of Puzzles Lib, you need v4.1.0 or higher.

**Comment by Ahley411** [comment]
> You have an outdated version of Puzzles Lib, you need v4.1.0 or higher.

I dont know where you'd prefer I put this so ill post in here. You were right on the Pu
zzles Lib outdated causing this, however, grabbing the latest caused serveral more issues. 
![crash](https://user-images.githubusercontent.com/72476191/182015846-231ef7ff-4c70-43eb-a336-991c2a12bc8c.jpg)
[latest.log](https://github.com/Fuzss/easymagic/files/9228261/latest.log)
Also, Visual Workbench now crashes the same way in popping up to the Launcher, when added. 

Here is the same crash with only puzzleslib and VisualWorkBench.
[latest.log](https://github.com/Fuzss/easymagic/files/9228263/latest.log)

**Comment by Fuzss** [comment]
You have outdated versions of all those mods. Puzzles Lib for 1.19.1 has breaking changes, you’ll have to use the latest version of all my mods for them to work. Visual Workbench hasn’t been updated yet, it doesn’t work on 1.19.1.

**Comment by Ahley411** [comment]
Thank you, all is working fine now, ill keep an eye out for a update on the workbench mod. Have a good one.

**Comment by Fuzss** [comment]
Here you go: https://www.curseforge.com/minecraft/mc-mods/visual-workbench/files/3910967
