### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by krn1c** [Fuzss/easymagic#16]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18

### Mod Version (Required)

4.0 

### Notes (Required)

I downloaded betterminecraft plus but the reroll was not working so I went into the config file and set it so reroll cost 0 lapiz but it seems to not work either way. Is there something I’m not doing right? can anyone tell me what exact thing to change in the config file for it to allow rerolls and be free?

**Comment by Fuzss** [comment]
Rerolls are a bit weird, by default they work just by taking the item you want to enchant from the enchanting slot and placing it back in.
Lapis and level costs only apply when you have set rerolls to "with cost", then you need to click the book in the gui.

It's not ideal like this, maybe I have a better idea that's easier to understand in the future.

**Comment by krn1c** [comment]
> Rerolls are a bit weird, by default they work just by taking the item you want to enchant from the enchanting slot and placing it back in. Lapis and level costs only apply when you have set rerolls to "with cost", then you need to click the book in the gui.
> 
> It's not ideal like this, maybe I have a better idea that's easier to understand in the future.

That’s weird. It wasn’t working by default that’s why I went into the config and changed it and it that still didn’t work. I’ll try setting it back to default again tomorrow to see if that fixes it or something.

**Comment by Fuzss** [comment]
It sometimes appears as if it's not working when the previous enchantments are selected again. Happens a lot actually when the table has no bookshelves since there aren't many enchants to select from at that point.
