### ISSUE TITLE
[Bug]: Crash on start-up

### ISSUE THREAD

**Issue by readyism** [Fuzss/easymagic#17]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19

### Mod Version (Required)

v4.10

### Notes (Required)

I cant open the game it pops up exit code 1 It only happens with this mod

**Comment by Fuzss** [comment]
You need v4.0.0 for 1.19. Also make sure to install the correct version of Puzzles Lib

**Comment by readyism** [comment]
I put the wrong version sorry it was late its happening with 1.19.1 Ive downloaded puzzles lib as well and it still doesnt work

**Comment by Fuzss** [comment]
Please send the crash-report: https://gist.github.com/Fuzss/9692f6ed5e8cca485a58004c28c9045b
