### ISSUE TITLE
[Suggestion]: Allow Placement of Vanilla Enchanting Tables

### ISSUE THREAD

**Issue by ZanderF0** [Fuzss/easymagic#25]
### Suggestion (Required)

Allow placement of enchanting tables with vanilla functionality without removing the mod and restarting the game to allow for easier compatibility with other mods.
e.g. https://modrinth.com/mod/ilmusuenchantments

**Comment by Fuzss** [comment]
Such a feature is not a feasible solution to this issue. That other mod also changes enchanting tables significantly, I don't want to invest the time to implement dedicated compatibility which would be required here. Just don't use Easy Magic if you want to use the other mod.
