### ISSUE TITLE
[Bug]: Variant Bookshelves lose enchanting power with Easy Magic

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/easymagic#29]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.3.3

### Notes (Required)

1. Install [Variant Bookshelves](https://www.curseforge.com/minecraft/mc-mods/variant-bookshelves-fabric) and Easy Magic
2. Create a world and build a full enchanting library with one of the VB's bookshelves (I used acacia ones)
3. Try to enchant an item with any level 3 enchantment
4. Instead there will only be level 1 enchantments, as if the library was not full

![2023-04-26_06 42 28](https://user-images.githubusercontent.com/86702831/234472352-60c11484-d6eb-498e-8713-77d95911e688.png)

Not sure which mod is at fault. Someone else opened an issue on VB before: https://github.com/xanthian/variant_bookshelves/issues/9. However, it has 0 details, so if the bug has to be fixed on their end, I'll copy the issue over.

### latest.log (Optional)

https://gist.github.com/SplendidAlakey/3bdf078b916d74308bc2e3e4fd7c2bec

**Comment by Fuzss** [comment]
They need to add their bookshelves to the Fabric bookshelves tag `c:bookshelves`.
