### ISSUE TITLE
Reroll at the cost of a level

### ISSUE THREAD

**Issue by SrBrahma** [Fuzss/easymagic#3]
Hey! I really liked your mod, and I intend to add it to my modpack, currently under development.

However, I don't like that free reroll system. It would make too easy for my tastes to get the desired enchantment.

I think if you could spend a level (and maybe a lapis), it would fit me better. Or at least, give the option in config to disable that reroll (does it already exists?). Better than having to enchant a wooden shovel but still not as "hacky" than the free reroll.

Thanks!

**Comment by Fuzss** [comment]
There are config options for everything Easy Magic has to offer, including this feature.

I might add something similar to the Reroll mod in the future, but no eta.
