### ISSUE TITLE
[Suggestion]: Compatibility with Wood Variants of Chiseled Bookshelves

### ISSUE THREAD

**Issue by Jusey1** [Fuzss/easymagic#32]
### Suggestion (Required)

I am currently working on updating my Woodster mod to make my wood variants of Chiseled Bookshelves into proper Chiseled Bookshelves and all (got it all working) and I was confused when testing it in the mod environment because I forgot Easy Magic did a few cool things with the vanilla Chiseled Bookshelf...

So, wanted to ask if it is possible to update the features to check for instanceof ChiseledBookShelfBlock instead of just only grabbing the specific vanilla block? I really like the feature of being able to see which book is in the shelf, haha. Using the instanceof check should automatically make it work with any Chiseled Bookshelf from any mod, if it is possible to use that is.

**Comment by Fuzss** [comment]
I changed this for 1.20, let me know if it works with your mod now or if it requires any other changes. Won't backport to 1.19.X though.

**Comment by Jusey1** [comment]
Danke, I haven't ported to 1.20 yet as I am waiting for Mojang to finish bugfixing it up and Forge to be more stable (we already have 1.20.1).
