### ISSUE TITLE
Mod completely not functional on server.[Bug]: 

### ISSUE THREAD

**Issue by Mahadbaloch** [Fuzss/easymagic#34]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20

### Mod Version (Required)

v7.0.0

### Notes (Required)

Hosting an aternos server which have easy anvils and easy magic installed among many other mods. Easy magic is the only one not working. All dependencies are installed and the server runs just fine, and the clients have all the same mods and can join and play normally, interacting with all mods, but easymagic is missing. It works on singleplayer, and the mod is in server files, it has a config in which I editing some values like the required bookshelves, but it does not work. No rerolls, no bookshelf amount changes, no lapis and item storage. Its like its not there. Is this some issue? Is there a separate version for server side? Because the config says server.toml and I have no idea what to do.

**Comment by Fuzss** [comment]
Break and replace the enchanting table.

**Comment by Mahadbaloch** [comment]
Lmao thanks sry
