### ISSUE TITLE
[Bug]: Reroll option unavailable

### ISSUE THREAD

**Issue by 0gdo** [Fuzss/easymagic#35]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.0

### Mod Version (Required)

v4.0.0

### Notes (Required)

When using the mod in a singleplayer world, the reroll button is not available to click. Items stay in the enchanting table and float around it after closing the menu, but the reroll button isn't present before or after enchanting an item. No resource packs are being used, and I cannot configure the reroll function using an alternative to Configured (the fabric version doesn't have a 1.19.0 version).

**Comment by Ibaudia** [comment]
I have a smiliar issue. Version 1.19.2 v4.3.3, Rerolling is only available before any enchantments are applied. Afterwards, the button is greyed out, but you can still click it. It will consume lapis and levels, and trigger the enchanting sound, but it will not reroll.

**Comment by Fuzss** [comment]
The reroll button is not available in 1.19, it was added in 1.19.2.

You can manually change the server config file in `.minecraft/saves/<world>/serverconfigs/easymagic-server.toml` to enable rerolling, it can be done by clicking the book model in the enchanting screen.
