### ISSUE TITLE
All enchantment list / config 

### ISSUE THREAD

**Issue by Pendertuga** [Fuzss/easymagic#4]
How do I change the config of the mod (in the "mod" option in the game menu it does not show a "config" option) bc i havent seen all enchantments and i want to see it

**Comment by Fuzss** [comment]
You either go to `.minecraft/config/easy-magic-common.toml` and change the appropriate value in that file, or you install the amazing [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) mod so you can modify the config from in-game.

Also please don't use the issue tracker for asking questions, the CurseForge page is for that.
