### ISSUE TITLE
[Suggestion]: Compatibility with Zenith mod (apotheosis for fabric)

### ISSUE THREAD

**Issue by PinkBoi333** [Fuzss/easymagic#41]
### Suggestion (Required)

Zenith's bookshelves offering eterna, quanta, arcana, and rectification are all negated and not counted as bookshelves. Placing an enchanting table and surrounding it with any bookshelf from Zenith mod isn't allowing it to register.

**Comment by Fuzss** [comment]
Support for Apotheosis / Zenith is not planned.

**Comment by PinkBoi333** [comment]
Ummm… then plan it.?
