### ISSUE TITLE
[Bug]: Setting the reroll catalyst via datapack doesnt disable the amethyst use

### ISSUE THREAD

**Issue by sprocketaudio** [Fuzss/easymagic#49]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.19.2

### Mod Version(s) (Required)

4.3.3

### Other Mods Involved (Required)

Yes

### Notes (Required)

When I create a datapack to set the reroll catalyst to a different item, the enchanting table still accepts amethyst and it still has the easymagic:reroll_catalysts tag. Is there a way to stop this?

![image](https://github.com/Fuzss/easymagic/assets/13222732/07f8d5fa-fa83-44ea-a3a5-972573055ebe)
![image](https://github.com/Fuzss/easymagic/assets/13222732/5be02521-96fb-47c0-8302-170cec85a7de)
![image](https://github.com/Fuzss/easymagic/assets/13222732/dbf813ff-d472-4e42-8201-169326827199)
[latest.log](https://github.com/Fuzss/easymagic/files/14187703/latest.log)

### latest.log (Required)

https://github.com/Fuzss/easymagic/files/14187703/latest.log

**Comment by Fuzss** [comment]
Set the `replace` property to `true`. 
https://minecraft.wiki/w/Tag#JSON_format

**Comment by sprocketaudio** [comment]
Thanks, sorry I didnt know this - I may have another issue though and it doesnt look like its covered in the lang file. I have successfully removed amethyst and added createdeco:gold_coin, however the reroll text still asks for amethyst! If I can add this to lang file what would it be called?

![image](https://github.com/Fuzss/easymagic/assets/13222732/13a9c1e4-4ab9-47fe-86d0-29848bb06bbb)
![image](https://github.com/Fuzss/easymagic/assets/13222732/b0cd39fa-377f-413e-8a58-38766a85ddb8)
![image](https://github.com/Fuzss/easymagic/assets/13222732/80bc35a2-07b1-4094-9604-e91eefe69634)
![image](https://github.com/Fuzss/easymagic/assets/13222732/032ffe16-643e-40a1-90db-de39295bc4af)

![image](https://github.com/Fuzss/easymagic/assets/13222732/049629f8-36af-46db-beff-10536412b9bf)

**Comment by Fuzss** [comment]
That's currently hardcoded to say Amethyst Shard. I'll track this in a new issue.

**Comment by sprocketaudio** [comment]
ok thank you
