### ISSUE TITLE
[Bug]: Enchantment table bug

### ISSUE THREAD

**Issue by saranghue** [Fuzss/easymagic#51]
### Mod Loader (Required)

⸺

### Minecraft Version(s) (Required)

1.19.4

### Mod Version(s) (Required)

1.19.4

### Other Mods Involved (Required)

⸺

### Notes (Required)

When I try to enchant a weapon/armor none of the available enchantments for that item shows up it is just blank. I have tried it in creative to check if it was minecraft but it worked in a creative world. 

### latest.log (Required)

https://gist.github.com/saranghue/b1646a78df1d208e6758624b39f0d7e4

**Comment by Fuzss** [comment]
Thanks for reporting! 1.19.4 is unfortunately not supported anymore.
