### ISSUE TITLE
[Suggestion]: Compatibility with Enchantment Reveal mod

### ISSUE THREAD

**Issue by polykatt** [Fuzss/easymagic#57]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

v8.0.1

### Suggestion (Required)

Currently the Enchantment Reveal mod does not work with this mod installed as well. Please consider adding compatibility with this mod so that they can work together.

**Comment by Fuzss** [comment]
Easy Magic has a config option for showing all the enchantments you will get.

**Comment by polykatt** [comment]
Oh, I had no idea - thank you!
