### ISSUE TITLE
Compatability problem with Enchanting Books mod

### ISSUE THREAD

**Issue by enginutku36** [Fuzss/easymagic#6]
Easy Magic mod is not compatabile with Enchanting Books mod. When I try to use the new iron, gold diamond or netherite books added from that mod in the enchanting table while Easy Magic is active I can't put them in the enchanting table. When I deactivate Easy Magic I can use those new books. Please fix soon.

**Comment by enginutku36** [comment]
@Fuzss

**Comment by Fuzss** [comment]
Fixed in 087b74d.
