### ISSUE TITLE
[Incompatibily]: Enchantment Reveal Not Works

### ISSUE THREAD

**Issue by Fyoncle** [Fuzss/easymagic#64]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.1

### Other Mods Involved (Required)

Yes

### Notes (Required)

Basically when you use [Easy Magic](https://modrinth.com/mod/easy-magic) and [Enchantment Reveal](https://modrinth.com/mod/enchantment-reveal) together, Easy Magic causing the Enchantment Reveal to disable.

### latest.log (Required)

No need.

**Comment by Fuzss** [comment]
There is no need for a separate mod, Easy Magic has this functionality built in, although you need to enable it in the server config: https://github.com/Fuzss/easymagic/blob/4d7ff85ffa87a1cde4a0345192b6f7b9c3df7bc8/1.21/Common/src/main/java/fuzs/easymagic/config/ServerConfig.java#L18
