### ISSUE TITLE
[Bug]: Chilcheled Bookshelves overlay disrupting player UI

### ISSUE THREAD

**Issue by ffuentesm** [Fuzss/easymagic#65]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.1

### Other Mods Involved (Required)

No

### Notes (Required)

As you can see, the text of the overlay is on the layer above the Player UI instead of behind it. 
![image](https://github.com/user-attachments/assets/17a2c394-ae93-4626-b0ff-157511cd6001)
![image](https://github.com/user-attachments/assets/9f7c72fa-01f6-42d2-a22b-7e68cf5c4b9e)

### latest.log (Required)

.

**Comment by Fuzss** [comment]
Thanks, fixed in Puzzles Lib v21.0.13.
