### ISSUE TITLE
[Crash]: Neoforge 21.0.82 changes crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [Fuzss/easymagic#66]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.1

### Other Mods Involved (Required)

No

### Notes (Required)

![image](https://github.com/user-attachments/assets/b8a914ae-636d-4de9-a0c1-c61d85ceab00)

### Crash Report (Required)

https://pastebin.com/pK5Frguu

**Comment by Fuzss** [comment]
Thanks, fixed in Puzzles Lib v21.0.13.
