### ISSUE TITLE
[Suggestion]: Easy Magic - Chiseled Bookshelves

### ISSUE THREAD

**Issue by ihymyly** [Fuzss/easymagic#67]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

v8.0.1

### Suggestion (Required)

Apotheosis/Zenith is currently not compatible Easy Magic, while both mods have very cool features. My proposal is to allow Chiseled Bookshelves to affect the enchantment table. Currently, Chiseled Bookshelves aren't that useful, even for decoration/storing enchanted books. One option is to make it similar to Apotheosis/Zenith's Seashelf of Aquatic Filtration. By inserting an enchanted book, you can remove that option from the list of possible enchantments. You can also go the route of improving the chances of that enchantment appearing, but I think the former is more usable. How it works is up to the developer, but I personally would appreciate some usefulness out of Chiseled Bookshelves. Thank you.

**Comment by ffuentesm** [comment]
They already do. there is a config that let you use chiseled bookshelves to power the table. You just need to add books to it, if you fill the bookshelves with 6 books, that gives a +2 to power.
