### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by MultiMaker-Studios** [Fuzss/easymagic#70]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21 Release

### Mod Version(s) (Required)

[FABRIC] [1.21] EasyMagic-v21.0.2

### Other Mods Involved (Required)

No

### Notes (Required)

As soon as try to open the game, fabric give me an error screen saying

"Some of your mods are incompatible with the game or each other!

  A potential solution has been determined, this may resolve your problem:
    Replace mod 'Fabric Loader' (fabricloader) 0.15.11 with version 0.16.0 or later.

  More details:
  Mod 'Easy Magic' (easymagic) 21.0.2 requires version 0.16.0 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.11!
  Mod 'Puzzles Lib' (puzzleslib) 21.0.18 requires version 0.16.0 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.11!
  Mod 'Forge Config API Port' (forgeconfigapiport) 21.0.7 requires version 0.16.0 or later of mod 'Fabric Loader'(fabricloader), but only the wrong version is present: 0.15.11!"

Unfortunately as I've just now come to realize, this has happened with other mods of yours previous which that I have tried, so this maybe be an issue on my end. 

Also this is my first time submitting a crash report and using Github, I'm sorry if the information I gave isn't what you needed or I gave incorrect or unhelpful information.

### Crash Report (Required)

https://gist.github.com/MultiMaker-Studios/f2dc29c47ab7003b6832df2e91464f38

**Comment by MultiMaker-Studios** [comment]
For other mods involved I meant to select yes as I do have a wide variety of mods installed

**Comment by Fuzss** [comment]
Reinstall Fabric with loader version 0.16.0.

**Comment by MultiMaker-Studios** [comment]
I just realized how stupid I am. I didn't realize that in the installer I had to scroll up to find .16 and thought it was some weird glitch. Thank you very much!
