### ISSUE TITLE
Dupe bug with Better-Shields

### ISSUE THREAD

**Issue by SharkieTV** [Fuzss/easymagic#8]
I did a report there [Basic-Shields](https://github.com/ToMe25/Better-Shields/issues/3). Your mod is allowing to dupe the shields when spamming left click in enchanting table

**Comment by Fuzss** [comment]
Yeah that's on me, Basic Shields has nothing to do with it. Problem is with shields in general, basically any item that is unstackable, but cannot receive enchantments at the enchanting table.

Fixed now as of v1.0.4 (1.16) and v2.0.1 (1.17).
