### ISSUE TITLE
[Suggestion]: Enchantment Description Support When Enchanting

### ISSUE THREAD

**Issue by thricebite** [Fuzss/easymagic#80]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.21.1

### Mod Version(s) (Optional)

21.1.0

### Suggestion (Required)

Add enchantment description to the selection tooltips

Easy Magic Tooltips:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/354e5bb3-9a33-4b84-9feb-93b9b3efa2e7">
Enchantment Description Tooltips:
<img src="https://cdn.modrinth.com/data/UVtY3ZAC/images/299554495de03058faaea236cb07aa418c5086aa.png">

**Comment by Fuzss** [comment]
Support has been added in v21.3.1.
