### ISSUE TITLE
[Bug]: "Keep Enchantment Screen Book" Setting Bugged.

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [Fuzss/easymagic#84]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.3

### Mod Version(s) (Required)

v21.3.1

### Other Mods Involved (Required)

Yes

### Notes (Required)

Setting "Keep Enchantment Screen Book" to "True" makes it so you can't Reroll your Enchantments, Clicking the Book does Nothing. The Actual Button Texture is also still Visible Behind the Book as well.

![2024-12-28_16 28 48](https://github.com/user-attachments/assets/c584ce0b-3cd9-4609-a413-79b3408414d7)
![2024-12-28_16 28 54](https://github.com/user-attachments/assets/a50f01c2-0f07-4b51-a3b6-94523ee2237c)

### latest.log (Required)

https://github.com/user-attachments/files/18267788/latest.log

**Comment by Fuzss** [comment]
Fixed in v21.3.2, thanks!
